version: '3'

services:
#    backend:
#      container_name: "spring-boot-webflux-app"
#      build:
#        context: .
#      ports:
#        - "8080:8080"
#      restart: always
#      depends_on:
#        - database
#      environment:
#        - HOST=localhost
#      networks:
#        - network-backend

    database:
      image: postgres:alpine
      container_name: "spring-boot-webflux-db"
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=webflux-db
      networks:
        - network-backend
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
networks: 
    network-backend:
        driver: bridge